# Generated by Django 4.2.11 on 2024-10-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_category_post_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Paddle Boarding', max_length=100),
        ),
    ]
