# Generated by Django 4.2.11 on 2024-10-18 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_post_image_post_proficiency_level_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
    ]
