# Generated by Django 4.2.11 on 2024-10-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, choices=[('free parking', 'Free Parking'), ('family friendly', 'Family Friendly'), ('no parking', 'No Parking'), ('pet friendly', 'Pet Friendly'), ('wheelchair accessible', 'Wheelchair Accessible')], max_length=50),
        ),
    ]
