# Generated by Django 4.2.11 on 2024-10-20 00:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_userprofile_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null='True', verbose_name='image'),
            preserve_default='True',
        ),
    ]
